# Generated by Django 6.0.7 on 2026-08-02 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='Passionate Linear Algebra Learner!')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('learning_streak', models.IntegerField(default=1)),
                ('last_activity_date', models.DateField(default=django.utils.timezone.now)),
                ('total_quiz_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
